sudo: required
services:
- docker
language: go
go:
- '1.11'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Wts8GEWxMkonLGCnxbMibgYJjsxqleDydU8lr73NxwlFpsFGGvWL1qE67K/fuI4hJpOhZX6pOKDTzXb/H/culINuftAPWxZdgv82Zy1q3uJawmyR82jGT/cWTomCwUYuE/okDSKWvkHrifroXIYGxYhetdeft8pPtI1IwXeXWozxBoJTTOxyBR5yUYBFKfQth3atf16cI/nTw8O/h6sePuULM7fJ1JDdHzaS9S7G6P3PBOPnKxhOgvVwlFXgmrYHHGA12dAaWQ8R7wkLWOtltCZvvIcAa14SWIREoRY0gqXg3ZqdRp9bCAUFCZmvoDcsTaKyEk+LWX7MtVZxx2iJBRlrtj+j8nKOcoktEybT854/kX7VTb3UgZIFoyLZCPI0JDy2Zjje71o2CdK/3wlNKAn7ls09jwWoINlM5RbQ0cF4DM1+j4LjTUdocC1/6NhuO72G8J9/MzxhpnXvUbk6iD0NW8Mkzwitv+LFykyVJ9qDiNE4W6fAp4pbVpjByzO7bRbRfhzXyD50t6RztCqbWdYekHc3etxmHOLpDBsVpdJK6rc3J1gj4+FTcc3iHp1zLcq5YXyLJRSC5hwYqFhfTSeaiD38nlj254hbKsP+tSOE7g8f9ml+jEe7HgLOfYBbxS6JeUOC/exTlrvgXdEQWhpFKRokeQOQiiTYr95KWBw=
  - secure: gS5u9wkysRBRjkIcw4/xhfXxyHOXhg9KoRQ/gWgWdlUQGHvS3VI6m6q+CZmjXFk96JdvgL5VPyUYmSAMdNgr6hwLHJd1DK63EzayqVCgjWCDMLXNjLnQN7ONSQ4kOk6Mb20/Cp176G5yG5C043BMdR6ViPLo5WH0bHx0xjboGezMR8BITMHRQ4Nj4Nj17ERVk2gwh2jHWA04gUNa8zfqeM70072eqC7FUJgYSMcsjq4ED17x9fONLLorTKHcyvEAfMgdJhub3qYvl2WkjzcFj6GjXMvhIhBsLGPYtPLlBq+yEoCECcJtUqJVnObEPLdZRFSNrEKyySSw5dYG0gpP9Tq5uxRXxQpOVREs+ITISW/6jnUdyD97GsoT7a6os0iPQek+WpPMeAti11bcGj8ZsZ4H1JfQEXwnF8Oiw2WXznoX8cKeWwGiO3bojPAXAhA0kKISQfuEP+5DgZbk2jy9FABBUuUHDnxO0vuPd1pUnvQF6g0oTjtZjYVGw6pURignfTzvBFqq0DgtD3IReCcMaghc3dao2OODAPfruIZDyDyQRtBvRQRqfH5TmrKGz7CFvfeF0AzZvjca3Va9KpjmL4Bxq1ruoyd/Lf5T8Is6uxtgH9dBa6gzmJDHjnFovug3PMfbDp8OvClz8betYGsOzKR21dFRYij7N58o7lJIfl8=
  - secure: H6qB1ez4l0K3CYJqac0hgkOhRa7aGu2rgQc+zdBGYn9ebhgJGQigsQ0Tci09E2XYj6d0fgXXC3huxemgHWIRdTP4wdlrF5kvwCBCq02BQZHjAvCrGAShP+rO33YkPgNwgx26ELYR8V18rW6PKI9eEE9nolvr+ZpAuzkneZZZ8yL80/nYSOOrZoTb0PznXHPVR4OWVVZZoCFv5pzJiXycZGWU4abwLS6g7Yw37GAIrP2Cs/hh5R72+RhVrceTGRJTPgYmyGa7H8D94OreZCRNR8K8AWmkYs5p52yaI8lo3YBo3Q5rsZqN+TAkVZESrlFrADtQSQu/A2MovwR1pO/qsj7w3KIohVI8C2raFov8UMepCvMbAXvytlJ+BYcsIpe7weKilKcmrIF37qwscmCvRPe/NlXbQfH1CU3CkrMKWoY/MTRCKe1yZFzysZBkyaKtIvKbi3peffzxQ2NAVr4rFmElt5NJA4NG1dt66cRefVI6b7DtW3MXuF4AwRCwcFI02yvY6WSpnteXs61IakQjAZ/zOgJyTr8AR/W8fAgxEdqL3XhNj4sTUR2ukJfbdw3cHoDURpsgDiYiKy+d5n6wjjJXURYJid6XOXiVO6Pmtm5w+mHIJTff2K4rvgIN5shwKD7ZBdS2uzH7uOstvvMnrpdNQE6kWyK+06vCJbuKJFM=
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=miclip/dotnet-resource
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
