sudo: required
services:
- docker
language: go
go:
- '1.11'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: vuf91cW1A4pl9/BQSZKb4GwkxHOzllN1a702Yxbqz8TMR9FNiDjg5kKRy//JcF45KuZBfdFjewHJ5RBc0RgbTazCrBc+gIKnXPAY+nGooNVkBKLhYj2dUI/cJ3eZ8JdA9sR3atn98riCJXEvmBNbkxBlx1gPGaBqBmVC4EhzWVQjMKGgwVMo+LYyVVwpvHjcDKBEdHovNBMCBCQ93scO2NwdDo6y5f8Ak0lZSH1uxwY6WwLr+A79wmBdQhwEbwKkp60UVZZKuJdVil4a/7J2pY+ofAV8bnO0P8vkgQ/1vfHgYsOKfkRhjvHV6VUCVxcL85XSpgkuzyTT/xkZETNW84NA4DYKaCq5YTk+/zU/QAxJKxfw+XYgCOa7lBthBjJH2R5QNiFRGyi9/81wYaO5JMcLNHglS5VDrHzC1f3txKehKaXg0B9qWFVhLEY39bSX4aHm364hlWg2y+ORSiePdlIxYn9FaYGLay0WtrTKsNb4DoAFJnHbOdF4ggQYaCVNCd/pK7c1ya2u88UIbEmxCMFVH5P8Rbbs8JyCQCi9oNx7b1blElL6Q1Jj66QU6Os0STSnnxLe8ZhY6yU7X456YrA1Bl0Z3Qn+d5HOqWfpVFBz3ZO5kLoNtO8fufcYYUVJccTLb2uuiNgrpPx7LL1jx7QQO8cUPn78CM77B99g0T4=
  - secure: poXFwC5aD3VcdPvnyjdaraJHGJCYCTpFOmWoGEfwEDfKHLSX+vwKsgwqv1TVUeUd4Fxh7UsFA1CnYT2z1eXOiW406E92DWUqhxYDI4dPD84PLRvGqvnHQb8o90Zd1Y9VcZFbsXj5yvSxTCVnWvUz2S/xb/vkfP7ZSTi5mtj+89t1twkiuwwcOEVVmylos+3fGWJ3Mcfb1UUsNxgJX9wF/FH2r0l/pkAaqtY/Ni/YiTcX1IeNDamYQbFgWjgBw6hUneL2fFcFzYt0O4EGbJNh4Jq1BUbk/TDanuzROnISUeh1v+Jokxr3XVlc7OpAcNwJnLDAXyQRUnQpoARo56yFiiwuz5dKxCzm9ZjZBGMCx8tZde0mgG3dzD3NOW+tCQVfnk0aMoYwtzPjU+0nyszsg73ubauiD1pYhzBxhxctSycsEmvNtDb77J8kM189mTY2/BgbOYBruiTv/aese0NMUKv8NgAVeNbTDNqsE/i4IF9f8Jwgz29C7uOaen1iYSx5h8CuqyQ7SNAj+YpV8PkVrPIQVsZsl7uIW7FwEqmhVJC9WFD9G1aidCh7WQEq7fBG1WvmBjR+PawFr+M9RsyCzvhZDGvjGA/ykrnoS2q1Nu+jtrLvvSgYVH3T5huHdhH5xJqxruny7gib7rCr9Ap4L2tbsixr9gZktDkCgc69yr4=
  - secure: mjYhv4Inm94AJtg83wVicLU6Jf4WYTo0HbDB9fg7jjIWsMEqYp/ubCPERDrPxxhFVr0gOweUm+jeNKu5eqroqI7Yi4k3XLpTeM7h3SdwcnMsB7NosYhheoxv/NGN46ayzEZE0qqy5RZPDvW+eOhbHe14bmfacNFJO+bBy1CgzkJ4B6YAfk3it+yPHpeGd3LN3ndgeFjJfFIZayD5P+qdRCN2GE+hnlvclLJUHRbHNbhOwMe8REynGezK8favdV28Ly67PyZKo08kPHrrLP8gcx/DOZWHMjSiEUXMFqL6OVl6upN6RNeJOUbMCcP4M/OwJK8N2ljpmCfPS+FdhgXni41MP4IbQLdUx1XQsFj6tisNxIL+EAGTrg32N2a4+x7w7HEs3+kXVmOwKYg7xjn9rQVoL/HT+u8lJnrcDNLnm8mO9pdt9SvZelJULgrnGRqQrLLvEKydXKN46Dp0VcdhlVtIHDCsYx09mTY05OYeYOlTcVJopwU3OVLT4O1iSVEW7Km/1UpukyeV3VdAJh92nG4cspFGHqtfKecc0RgH+eyGN4brk5owKpCjsMnW49bpH0Df+jm32qCJSfgXXSGhD0Bob8z8K2UprnEpAwFhYmA81XY1XZrx9EwNUK3naEieNNMPPHQSotGa4O9STcd0yBWiCpD3ilJ8Ikv3oCYed08=
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=miclip/dotnet-resource
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
